stages:
  - gitleaks
  - kics
  - docker-build
  - snyk
  - docker-push

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  AWS_REGION: eu-west-3
  AWS_ACCOUNT:
  ECR_REGISTRY: $AWS_ACCOUNT.dkr.ecr.$AWS_REGION.amazonaws.com
  ECR_REPOSITORY: contest
  IMAGE_WITH_TAG: $ECR_REGISTRY/$ECR_REPOSITORY:latest

gitleaks-job:
  stage: gitleaks
  image:
    name: "zricethezav/gitleaks"
    entrypoint: [""]
  script:
    - gitleaks detect -v --report-path gitleaks-report.json -c gitleaks.toml
  artifacts:
    when: always
    paths:
      - gitleaks-report.json
    expire_in: 1 hour

kics-scan-job:
  stage: kics
  image:
    name: checkmarx/kics:latest
    entrypoint: [""]
  script:
    - ls
    - kics scan --fail-on "high" --no-progress -p ${PWD} -e ${PWD}/vpc.tf -e ${PWD}/alb.tf
  allow_failure: true

# docker-build-job:
#   stage: docker-build
#   image:
#     name: docker:latest
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker
#   script:
#     # TODO

# snyk-scan-job:
#   stage: snyk
#   image:
#     name: snyk/snyk:docker-latest
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker
#   dependencies:
#     # TODO
#   needs:
#     # TODO
#   script:
#     # TODO

# snyk-pages-job:
#   stage: snyk
#   image:
#     name: node:latest
#     entrypoint: [""]
#   dependencies:
#     # TODO
#   needs:
#     # TODO
#   before_script:
#     # TODO
#   script:
#     # TODO

# docker-push-job:
#   stage: docker-push
#   image:
#     name: amazon/aws-cli
#     entrypoint: [""]
#   services:
#     - name: docker:dind
#       alias: docker
#   dependencies:
#     # TODO
#   needs:
#     # TODO
#   before_script:
#     # TODO
#   script:
#     # TODO
